const {
  REACT_APP_POLYGON_EDGE_API,
  REACT_APP_POLYGON_EDGE_CHAIN_ID,
  REACT_APP_MVPT_ADDRESS,
  REACT_APP_TICKET_SALE_ADDRESS
} = process.env;

if (!REACT_APP_POLYGON_EDGE_API) {
  throw Error('REACT_APP_POLYGON_EDGE_API property not found in .env');
}

if (!REACT_APP_POLYGON_EDGE_CHAIN_ID) {
  throw Error('REACT_APP_POLYGON_EDGE_CHAIN_ID property not found in .env');
}

if (!REACT_APP_MVPT_ADDRESS) {
  throw Error('REACT_APP_MVPT_ADDRESS property not found in .env');
}

if (!REACT_APP_TICKET_SALE_ADDRESS) {
  throw Error('REACT_APP_TICKET_SALE_ADDRESS property not found in .env');
}

export default {
  POLYGON_EDGE_API: REACT_APP_POLYGON_EDGE_API,
  POLYGON_EDGE_CHAIN_ID: REACT_APP_POLYGON_EDGE_CHAIN_ID,
  MVPT_ADDRESS: REACT_APP_MVPT_ADDRESS,
  TICKET_SALE_ADDRESS: REACT_APP_TICKET_SALE_ADDRESS
};
